### ISSUE TITLE
does archistar-bft have been used in production enviroment?

### ISSUE THREAD

**Issue by young001** [Archistar/archistar-bft#1]
does archistar-bft have been used in production enviroment?
which project use archistart-bft?

thx

**Comment by andreashappe** [comment]
Hi, short answer: no. Longer answer: we were using archistar-bft within the archistar.at researchproject and a newer version of it (javascript-based) as part of the prismacloud.eu research project.

HTH, Andreas

**Comment by young001** [comment]
thx
